services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Application\Department\UseCases\Handlers\:
        resource: '%kernel.project_dir%/src/Application/Department/UseCases/Handlers/'
