services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Application\Geo\GeoLocationServiceInterface:
        class: Infrastructure\Geo\GeoLocationService
