version: '3'

services:
    mysql:
        image: mysql:8.0
        command: "--lower-case-table-names=1 --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
        container_name: code_examples_mysql
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        ports:
            - "3336:3306"
        volumes:
            - mysql-data:/var/lib/mysql:rw
            - ./mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
            - ./mysql/init:/docker-entrypoint-initdb.d

    php:
        build:
            context: ./php
            args:
                USER_ID: ${USER_ID}
                USER_NAME: ${USER_NAME}
                GROUP_ID: ${GROUP_ID}
                GROUP_NAME: ${GROUP_NAME}
                XDEBUG_ON: ${XDEBUG_ON}
                XDEBUG_MODE: ${XDEBUG_MODE}
                XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
                XDEBUG_PORT: ${XDEBUG_PORT}
        container_name: code_examples_php
        environment:
            - PHP_IDE_CONFIG=serverName=${XDEBUG_TRIGGER}
            - XDEBUG_TRIGGER=${XDEBUG_TRIGGER}
        ports:
            - 9000
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ../:/var/www/public
            - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini

    workspace:
        build:
            context: ./php
            args:
                USER_ID: ${USER_ID}
                USER_NAME: ${USER_NAME}
                GROUP_ID: ${GROUP_ID}
                GROUP_NAME: ${GROUP_NAME}
                XDEBUG_ON: ${XDEBUG_ON}
                XDEBUG_MODE: ${XDEBUG_MODE}
                XDEBUG_IDEKEY: ${XDEBUG_IDEKEY}
                XDEBUG_PORT: ${XDEBUG_PORT}
        container_name: code_examples_workspace
        environment:
            - PHP_IDE_CONFIG=serverName=${XDEBUG_TRIGGER}
            - XDEBUG_TRIGGER=${XDEBUG_TRIGGER}
        ports:
            - 9000
        extra_hosts:
            - "host.docker.internal:host-gateway"
        command: bash -c "
            COMPOSER_MEMORY_LIMIT=-1 composer install --optimize-autoloader
            && php bin/console cache:clear
            && php bin/console doctrine:migrations:migrate
            "
        volumes:
            - ../:/var/www/public

    node:
        build:
            context: ./node
            args:
                USER_ID: ${USER_ID}
                USER_NAME: ${USER_NAME}
                GROUP_ID: ${GROUP_ID}
                GROUP_NAME: ${GROUP_NAME}
        container_name: code_examples_node
        ports:
            - 3000:3000
        volumes:
            - ../:/var/www/project

    nginx:
        build:
            context: ./nginx
            args:
                USER_ID: ${USER_ID}
                USER_NAME: ${USER_NAME}
                GROUP_ID: ${GROUP_ID}
                GROUP_NAME: ${GROUP_NAME}
        container_name: code_examples_nginx
        ports:
            - 80:80
        volumes:
            - ../:/var/www/public
            - ./nginx/sites:/etc/nginx/conf.d

volumes:
    mysql-data:
